feat(CD): Automatic blue/green deployment
Signed-off-by: Paul Brissaud <pbrissaud.pro@gmail.com>

diff --git a/.github/workflows/releasing.yaml b/.github/workflows/releasing.yaml
--- a/.github/workflows/releasing.yaml
+++ b/.github/workflows/releasing.yaml
@@ -75,6 +75,8 @@ jobs:
     name: Deploy to Cloud Run
     runs-on: ubuntu-latest
     needs: docker
+    outputs:
+      url: ${{ steps.deploy.outputs.url }}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -88,8 +90,55 @@ jobs:
 
       - name: Deploy to Cloud Run
         uses: google-github-actions/deploy-cloudrun@v2
+        id: deploy
         with:
           service: ${{ github.event.repository.name }}
           region: ${{vars.REGION}}
           project_id: ${{vars.PROJECT_ID}}
           image: ${{vars.REGION}}-docker.pkg.dev/${{vars.PROJECT_ID}}/${{ vars.ARTIFACT_REGISTRY }}/${{ github.event.repository.name }}@${{needs.docker.outputs.image_digest}}
+          no_traffic: true
+          tag: green
+          
+  promote:
+    name: Blue-green deployment
+    runs-on: ubuntu-latest
+    needs: deploy
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Login to Google Cloud
+        id: auth
+        uses: google-github-actions/auth@v2
+        with:
+          workload_identity_provider: ${{ secrets.PROVIDER_NAME }}
+          service_account: ${{ secrets.SA_EMAIL }}
+
+      - name: Install k6
+        run: |
+          sudo gpg -k
+          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
+          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
+          sudo apt-get update
+          sudo apt-get install k6
+
+      - name: Gradually increase traffic
+        run: |
+          echo ${{ needs.deploy.outputs.url }}
+          for traffic in 10 25 50 75 100; do
+            echo "Shifting ${traffic}% traffic to the new revision"
+            gcloud run services update-traffic ${{github.event.repository.name}} --to-tags green=${traffic} --region ${{vars.REGION}} --project ${{vars.PROJECT_ID}}
+            URL=${{ needs.deploy.outputs.url }} k6 run k6s.js
+            
+            if [ $? -ne 0 ]; then
+              echo "k6 tests failed at ${traffic}% traffic, rolling back!"
+              gcloud run services update-traffic ${{github.event.repository.name}} --to-tags green=0 --region ${{vars.REGION}} --project ${{vars.PROJECT_ID}}
+              exit 1
+            fi
+          done
+
+          gcloud run services update-traffic ${{github.event.repository.name}} --region ${{vars.REGION}} --project ${{vars.PROJECT_ID}} --remove-tags blue,green
+          LATEST=$(gcloud run services list --region ${{vars.REGION}} --project ${{vars.PROJECT_ID}} --service=${{github.event.repository.name}} --sort-by="~createTime" --limit=1 --format="value(metadata.name)")
+          gcloud run services update-traffic ${{github.event.repository.name}} ---region ${{vars.REGION}} --project ${{vars.PROJECT_ID}} --set-tags blue=${LATEST}
+
+
